on:
  push:
    branches:
      - main
      - 'releases/**'


  #   tags:
  #     - v*
  #   branches-ignore:
  #     - main
  # pull_request:
  #   branches:
  #     - main

name: Release Build

jobs:
  amd64docker:
    runs-on: ubuntu-latest
    name: Docker (amd64) + publish
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta (tag)
        if: startsWith(github.ref, 'refs/tags/')
        id: meta_tag
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/wouterdebie/putioarr
          tags: |
            latest
            type=semver,pattern={{version}}

      - name: Docker meta (branch)
        if: startsWith(github.ref, 'refs/heads/')
        id: meta_branch
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/wouterdebie/putioarr
          tags: |
            type=ref,event=branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker images (tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta_tag.outputs.tags }}
          push: true
          platforms: linux/amd64

      - name: Build and push Docker images (branch)
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta_branch.outputs.tags }}
          push: true
          platforms: linux/amd64
