on:
  push:
    branches:
      - main
      - 'releases/**'
    tags:
      - v*
  #   branches-ignore:
  #     - main
  # pull_request:
  #   branches:
  #     - main

name: Release Build

jobs:
  amd64docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    name: Docker + publish
    steps:
      - uses: actions/checkout@v4
      - name: Docker meta (tag)
        if: startsWith(github.ref, 'refs/tags/')
        id: meta_tag
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/wouterdebie/putioarr
          tags: |
            latest
            type=semver,pattern={{version}}

      - name: Docker meta (branch)
        if: startsWith(github.ref, 'refs/heads/')
        id: meta_branch
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/wouterdebie/putioarr
          tags: |
            type=ref,event=branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker images (tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          tags: ${{ steps.meta_tag.outputs.tags }}
          push: true
          provenance: false
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker images (branch)
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          tags: ${{ steps.meta_branch.outputs.tags }}
          push: true
          provenance: false
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
